version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  scholar-scraper:
    build: ./apps/scholar-scraper
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - rabbitmq
